// solidjs-search-anime/src/components/Header.tsx
import { NavLink } from '@solidjs/router';
import { Component } from 'solid-js';

export const Header: Component = () => {
  return (
    <header>
      <nav class='navbar navbar-expand-lg bg-light'>
        <div class='container-fluid'>
          <div class='navbar-brand'>SolidJS</div>
          <div class='navbar-nav'>
            <NavLink class='nav-link' href='/home'>
              Home
            </NavLink>
            <NavLink class='nav-link' href='/about'>
              About
            </NavLink>
          </div>
        </div>
      </nav>
    </header>
  );
};

// reactjs-search-anime/src/components/Header.tsx
import { NavLink } from 'react-router-dom';
export const Header: React.FC = () => {
  return (
    <header>
      <nav className='navbar navbar-expand-lg bg-light'>
        <div className='container-fluid'>
          <div className='navbar-brand'>ReactJS</div>
          <div className='navbar-nav'>
            <NavLink className='nav-link' to='/home'>
              Home
            </NavLink>
            <NavLink className='nav-link' to='/about'>
              About
            </NavLink>
          </div>
        </div>
      </nav>
    </header>
  );
};
