// solidjs-search-anime/src/App.tsx
import { Component, ErrorBoundary, lazy } from 'solid-js';
import { RouteDefinition, Router, useRoutes } from '@solidjs/router';
import { Header } from './components/Header';

const routes: RouteDefinition[] = [
  {
    path: '/',
    component: lazy(() => import('./pages/Home')),
  },
  {
    path: '/home',
    component: lazy(() => import('./pages/Home')),
  },
  {
    path: '/about',
    component: lazy(() => import('./pages/About')),
  },
  {
    path: '/anime/:id',
    component: lazy(() => import('./pages/Home')),
  },
];
const App: Component = () => {
  const Routes = useRoutes(routes);
  return (
    <Router>
      <ErrorBoundary fallback={(err) => err}>
        <Header />
        <div class='container'>
          <Routes />
        </div>
      </ErrorBoundary>
    </Router>
  );
};

export default App;

// reactjs-search-anime/src/App.tsx
import './App.scss';
import About from './pages/About';
import Home from './pages/Home';
import Anime from './pages/Anime';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';

const App: React.FC = () => {
  const router = createBrowserRouter([
    {
      path: '/',
      element: <Home />,
      errorElement: <div>Error</div>,
    },
    {
      path: '/home',
      element: <Home />,
      errorElement: <div>Error</div>,
    },
    {
      path: 'about',
      element: <About />,
    },
    {
      path: 'anime/:id',
      element: <Anime />,
    },
  ]);
  return <RouterProvider router={router} />;
};

export default App;
