// reactjs-search-anime/src/components/AnimeDetail.tsx
import { useState, useEffect } from 'react';
import { fetchAnimeById } from '../api/anime';
import { AnimeData } from '../model/anime.model';
import { Loader } from './Loader';

interface AnimeDetailProps {
  id: string;
}

export const AnimeDetail: React.FC<AnimeDetailProps> = ({ id }) => {
  const [animeData, setAnimeData] = useState<AnimeData | null>(null);
  const [error, setError] = useState<{ details: string } | null>(null);
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    (async () => {
      setLoading(true);
      const { response, error } = await fetchAnimeById(id);
      setAnimeData(response);
      setError(error);
      setLoading(false);
    })();
  }, [id]);

  if (!animeData || error)
    return (
      <div className='alert alert-primary' role='alert'>
        {error?.details}
      </div>
    );
  if (loading) return <Loader />;

  return (
    <div className='container d-flex flex-column align-items-center my-5'>
      <div className=''>
        <img className='rounded' src={animeData.main_picture?.large} alt={animeData.title} />
      </div>
      <h3 className='my-3 '>
        <strong>{animeData.title}</strong>
      </h3>
      <p className='w-50'>{animeData.synopsis}</p>
    </div>
  );
};

// solidjs-search-anime/src/components/AnimeDetail.tsx
import { Component, createResource, Match, Switch } from 'solid-js';
import { fetchAnimeById } from '../api/anime';
import { Loader } from './Loader';

interface AnimeDetailProps {
  id: string;
}

export const AnimeDetail: Component<AnimeDetailProps> = ({ id }) => {
  const [animeData] = createResource(() => id, fetchAnimeById);
  return (
    <Switch
      fallback={
        <div class='alert alert-primary' role='alert'>
          {animeData()?.error?.details}
        </div>
      }
    >
      <Match when={animeData.loading}>
        <Loader />
      </Match>
      <Match when={!!animeData()?.response}>
        <div class='container d-flex flex-column align-items-center my-5'>
          <div class=''>
            <img
              class='rounded'
              src={animeData()?.response?.main_picture?.large}
              alt={animeData()?.response?.title}
            />
          </div>
          <h3 class='my-3 '>
            <strong>{animeData()?.response?.title}</strong>
          </h3>
          <p class='w-50'>{animeData()?.response?.synopsis}</p>
        </div>
      </Match>
    </Switch>
  );
};
